### ISSUE TITLE
LibraryManager 빌리다, 반납하다 구현

### ISSUE THREAD

**Issue by seung-00** [BlessingDev/Library-Mangement-System#13]

**Comment by BlessingDev** [comment]
LibraryManager에서 기능을 수행할 때 리스트에서 BookInfo 객체를 받아와서 수행하게 되는데 이 때 받는 객체가 Call by value인지 Call by reference/pointer인지 유의해야 합니다.
이거는 전체적인 구조에 대한 고려가 필요한 부분입니다.
이 부분은 다시 의논하는 걸로 하겠습니다.

**Comment by seung-00** [comment]
bookinfo 복사 포인터로?
