### ISSUE TITLE
SPV로 인한 Borrow, Reserve 수정

### ISSUE THREAD

**Issue by seung-00** [BlessingDev/Library-Mangement-System#33]
Borrow 할 때
1. if(!Q empty) top이 자기 자신이면 borrow
2. Q full
2. 대여권수 체크
3. penalty 체크

각각 에러 코드 보내기

Reserve도
1. penalty
2. penalty 받으면 예약 취소
3. Q full?
4. Q empty -> borrow

각각 에러 코드 보내기

**Comment by BlessingDev** [comment]
- 날짜 계산(예약, 페널티)
- 페널티 포인터화 해서 nullptr이면 페널티 없는 걸로
- BorrowInfo의 BookInfo와 UserInfo는 포인터로
