### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by halee0** [BlessingDev/Library-Mangement-System#40]
1. lab에 나온 run함수를 토대로 만들어서 반환형을 void->int로 변경
2. search함수에서 통합검색/기준따라 검색 선택하는 기능 구현필요
3. Return, DisplayDelayedBook함수 추가
4. 도서리스트, 이용자리스트 display함수도 필요할까요?
5. 입력을 string으로 받기로 했는데 깜빡하고 int로 받았습니당...고칠내용 생기면 함께 수정하겠습니다.

**Comment by BlessingDev** [comment]
4. 네 있어야 할 것 같습니다.
5. 구현 방식이야 최종적으로 잘 돌아가기만 한다면 상관 없습니다.
