### ISSUE TITLE
Application/LibraryManager수정

### ISSUE THREAD

**Issue by halee0** [BlessingDev/Library-Mangement-System#55]
1. LibraryManager 통합검색에서 검색되지 않았을 경우 다시 for문을 돌기위해 break->continue로 수정
2. Application에서 mode선택시 종료되지 않는 부분 수정
3. book/user메뉴에서 0 선택시 다시 mode로 돌아가도록 수정

위의 부분 수정완료했습니다.

**Comment by BlessingDev** [comment]
완료됐으니 닫겠습니다.
